version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-eks: circleci/aws-eks@2.1.0

jobs:
  lint-code:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            make install
      - run:
          name: Lint Code
          command: |
            make lint

workflows:
    example-workflow:
      jobs:
        # - lint-code
        # - aws-ecr/build-and-push-image:             
        #     aws-access-key-id: AWS_ACCESS_KEY_ID 
        #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
        #     region: AWS_REGION 
        #     account-url: AWS_ECR_ACCOUNT_URL
        #     create-repo: true 
        #     dockerfile: Dockerfile 
        #     path: .             
        #     repo: capstone         
        #     requires: [ lint-code ]  

        - aws-eks/create-cluster:
            cluster-name: capstoneCluster 
            aws-region: AWS_REGION 
            show-eksctl-command: true

        - aws-eks/update-container-image:
            show-kubectl-command: true 
            cluster-name: capstoneCluster 
            container-image-updates: CONTAINER_NAME_1=524381496777.dkr.ecr.us-east-1.amazonaws.com/capstone:latest 