version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.0
  kubernetes: circleci/kubernetes@1.0

jobs:

  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:      
      - aws-eks/create-cluster:
          cluster-name: cluster-name
          skip-kubectl-install: false
          show-eksctl-command: true
          verbose: 3
          node-type: t2.micro
          nodes-max: 2
          ssh-access: true
          ssh-public-key: 'Ansible-Ec2.pem'

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster
          
workflows:
  deployment:
    jobs:
    
      - create-cluster:
          cluster-name: capstoneCluster

      - test-cluster:
          cluster-name: capstoneCluster
          requires:
            - create-cluster

      # - aws-eks/delete-cluster:
      #     cluster-name: capstoneCluster
      #     requires:
      #       - test-cluster
