version: 2.1
orbs:
  aws-eks: circleci/aws-eks@0.2.3
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.4.0

workflows:
  default:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: eks-capstone      