version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0



workflows:
    example-workflow:
      jobs:
        - aws-ecr/build-and-push-image:             
            aws-access-key-id: AWS_ACCESS_KEY_ID 
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
            region: AWS_REGION 
            account-url: AWS_ECR_ACCOUNT_URL
            create-repo: true 
            dockerfile: Dockerfile 
            path: .             
            repo: capstone           