apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-capstone
  namespace: eks-capstone-ns
  labels:
    app: eks-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-capstone
  template:
    metadata:
      labels:
        app: eks-capstone
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
        - name: capstone
          image: 524381496777.dkr.ecr.us-east-1.amazonaws.com/capstone:latest
          ports:
          - name: http
            containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
          kubernetes.io/os: linux