apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-capstone
  namespace: eks-capstone-ns
  labels:
    app: eks-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-capstone
  template:
    metadata:
      labels:
        app: eks-capstone
    spec:
      # containers:
      # - name: nginx
      #   image: public.ecr.aws/nginx/nginx:1.21
      #   ports:
      #   - name: http
      #     containerPort: 80
      #   imagePullPolicy: Always      
      
      containers:
        - name: capstone
          image: 524381496777.dkr.ecr.us-east-1.amazonaws.com/capstone:latest
          ports:
          - name: http
            containerPort: 80
          imagePullPolicy: Always
